name: Get Unity License ULF

on:
  workflow_dispatch:

jobs:
  generate-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate ULF File from Unity
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          UNITY_VER=$(grep "m_EditorVersion:" MoayadAR/ProjectSettings/ProjectVersion.txt | awk '{print $2}')
          echo "Target Unity Version: $UNITY_VER"

          docker run --rm \
            -v ${{ github.workspace }}:/project \
            unityci/editor:ubuntu-${UNITY_VER}-base-3 \
            bash -c "unity-editor -batchmode -nographics -username '$UNITY_EMAIL' -password '$UNITY_PASSWORD' -logfile /dev/stdout || true; cp /root/.local/share/unity3d/Unity/*.ulf /project/UnityLicense.ulf || true"

      - name: Upload ULF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityLicenseFile
          path: ./UnityLicense.ulf
