name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: MoayadAR

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MoayadAR-APK
          path: build/Android/**/*.apk
