name: Build MoayadAR Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Unity Android APK 📱
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free Disk Space for Unity
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: false
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false

      - name: Build Unity Project (Android)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: Android
          projectPath: MoayadAR
          androidAppBundle: false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoayadAR-App-APK
          path: build/Android/*.apk
